version: "3.9"

services:
  java:
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ..:/workspaces/java
    # This is where ports would go
    networks:
      - java-network
  # Additional services here
# Volumes here
networks:
  java-network:
    driver: bridge
    